name: Build & Test

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C instrument-coverage"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate code coverage
      uses: taiki-e/cargo-llvm-cov@v1
      with:
        # The format of the output. One of "html", "lcov", "json", or "text".
        # Defaults to "html".
        output-format: lcov

        # The name of the output file. Defaults to "coverage.lcov".
        output-filename: lcov.info

        # The directory where the output file will be saved. Defaults to "./coverage".
        output-directory: ./coverage
    - name: coverage
      uses: coverallsapp/github-action@v2
      with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: "./coverage"
