name: Build & Test

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C instrument-coverage"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: add rust coverage tooling
      run: |
        cargo install cargo-tarpaulin
    - name: run test coverage
      run: |
        cargo tarpaulin --workspace
    - name: coverage
      uses: coverallsapp/github-action@v2
      with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
